### ISSUE TITLE
Memory hot unplug feature is not available in 'hostos-devel' branch

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#1]
Memory hot unplug feature not available in 'hostos-devel' branch.

How to re-produce:
1. Hot plug the memory using the following command and xml
# cat mem_hp.xml

<memory model='dimm'>
<target>
<size unit='KiB'>262144</size>
</target>
</memory>

Before attaching memory at Guest:
[root@localhost ~]# cat /proc/meminfo | grep -i memtotal
MemTotal:        7838848 kB

Attach memory, here 
# virsh attach-device centos72 mem_hp.xml --live

Device attached successfully

After attach guest memory:
[root@localhost ~]# cat /proc/meminfo | grep -i memtotal
MemTotal:        8100992 kB
1. Try to detach memory using the following command and xml
   # cat /tmp/t1   # Detach memory xml, taken from virsh dumpxml <domain>
   <memory model='dimm'>
     <target>
       <size unit='KiB'>262144</size>
     </target>
     <alias name='dimm0'/>
     <address type='dimm' slot='0' base='0x200000000'/>
   </memory>
# virsh detach-device centos72 /tmp/t1 --live

error: Failed to detach device from /tmp/t1
error: internal error: unable to execute QEMU command 'device_del': Memory hot unplug not supported by sPAPR

Additional information:
Guest is having powerpc-utils at 1.3.0 level.

**Comment by nasastry** [comment]
xml files for memory hot plug and memory hot unplug got mangled so created as attachments.
[mem_hp.xml.txt](https://github.com/open-power-host-os/qemu/files/444599/mem_hp.xml.txt)
[mem_unplug.xml.txt](https://github.com/open-power-host-os/qemu/files/444600/mem_unplug.xml.txt)

**Comment by rmatinata-ibm** [comment]
@aik can you, or somebody else appropriate, take a look into this ?

**Comment by aik** [comment]
The appropriate persons are Mike Roth @mdroth  and Bharata B Rao bharata@linux.vnet.ibm.com (who does not seem to be on github and we need to invite him here).

**Comment by nasastry** [comment]
Closing the issue here and this is handled at bugzilla.
