### ISSUE TITLE
qemu crashed during "info cpus" in monitor with change in default cpu in hotplug/unplug sequence

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/qemu#11]
Qemu
qemu process crashed during info cpus query with default cpu index changed with hotplug/unplugged cpu

1. Boot the guest with below command line
2. hotplug vcpu 1
3. change the default cpu to vcpu1
4. unplug vcpu 1
5. issue `info cpus` in monitor
===> qemu process get terminated with this print "qemu:qemu_cpu_kick_thread: No such process"

```
# qemu-kvm -M pseries,max-cpu-compat=power9,accel=kvm -smp 1,cores=1,threads=1,sockets=1,maxcpus=2 -m 256 -nographic -enable-kvm /home/sath/hostos-3.0-ppc64le.qcow2 -monitor stdio -serial /dev/pts/1
QEMU 2.10.0 monitor - type 'help' for more information
(qemu) info cpus
* CPU #0: nip=0x000000000dbe1eb8 thread_id=74473
(qemu) info hotpluggable-cpus
Hotpluggable CPUs:
  type: "host-spapr-cpu-core"
  vcpus_count: "1"
  CPUInstance Properties:
    core-id: "1"
  type: "host-spapr-cpu-core"
  vcpus_count: "1"
  qom_path: "/machine/unattached/device[0]"
  CPUInstance Properties:
    core-id: "0"

2. (qemu) device_add host-spapr-cpu-core,id=core1,core-id=1
(qemu) info cpus
* CPU #0: nip=0xc0000000000b190c thread_id=74473
  CPU #1: nip=0xc0000000000b190c thread_id=74553

3.(qemu) cpu 1
(qemu) info cpus
  CPU #0: nip=0xc0000000000b190c thread_id=74473
* CPU #1: nip=0xc0000000000b190c thread_id=74553

4. (qemu) device_del core1

5.(qemu) info cpus
qemu:qemu_cpu_kick_thread: No such process


```

<cde:info> Mirrored with LTC bug #159869 </cde:info>

**Comment by sathnaga** [comment]
Able to reproduce on upstream commit aswell https://github.com/qemu/qemu/commit/530049bc1dcc24c1178a29d99ca08b6dd08413e0

**Comment by cdeadmin** [comment]
------- Comment From KURZGREG@fr.ibm.com 2017-10-13 04:51:50 EDT-------
Fix posted to upstream list:

https://lists.nongnu.org/archive/html/qemu-devel/2017-10/msg03060.html

Note that this series is based on the ppc maintainer staging tree:

https://github.com/dgibson/qemu/commits/ppc-for-2.11

**Comment by cdeadmin** [comment]
------- Comment From satheera@in.ibm.com 2017-10-13 07:49:25 EDT-------
(In reply to comment #3)
&gt; Fix posted to upstream list:
&gt; 
&gt; https://lists.nongnu.org/archive/html/qemu-devel/2017-10/msg03060.html
&gt; 
&gt; Note that this series is based on the ppc maintainer staging tree:
&gt; 
&gt; https://github.com/dgibson/qemu/commits/ppc-for-2.11

Hi Greg,

Could you please add Reported-by : Satheesh Rajendran &lt;sathnaga@linux.vnet.ibm.com&gt; .

Thanks in advance.

Regards,
-Satheesh.

**Comment by cdeadmin** [comment]
------- Comment From KURZGREG@fr.ibm.com 2017-11-06 09:04:46 EDT-------
(In reply to comment #4)
&gt; 
&gt; Hi Greg,
&gt; 
&gt; Could you please add Reported-by : Satheesh Rajendran
&gt; &lt;sathnaga@linux.vnet.ibm.com&gt; .
&gt; 
&gt; Thanks in advance.
&gt; 
&gt; Regards,
&gt; -Satheesh.

Final fix (with added Reported-by :) is now upstream.

https://git.qemu.org/?p=qemu.git;a=commit;h=751f8cfe2a556b3ef49f6af2860e2d1d2a1ec66a

Since this is isn't a blocking bug, it will be applied to HostOS when Alexey rebases to QEMU 2.11 (to be released in December).

**Comment by cdeadmin** [comment]
------- Comment From satheera@in.ibm.com 2017-12-20 04:21:55 EDT-------
Tested with qemu-kvm-2.11.0-1.rel.gite7153e0.el7.centos.ppc64le and issue if fixed.

# qemu-kvm -M pseries,max-cpu-compat=power9,accel=kvm -smp 1,cores=1,threads=1,sockets=1,maxcpus=2 -m 256 -nographic -enable-kvm /home/sath/hostos-ppc64le.qcow2 -monitor stdio -serial /dev/pts/1
QEMU 2.11.0 monitor - type 'help' for more information
(qemu) info cpus
* CPU #0: nip=0x000000000dc02ec0 thread_id=91678
(qemu) device_add host-spapr-cpu-core,id=core1,core-id=1
(qemu)  cpu 1
(qemu) info cpus
  CPU #0: nip=0xc0000000000b715c thread_id=91678
* CPU #1: nip=0xc0000000000b715c thread_id=91786
(qemu)  device_del core1
(qemu) info cpus
* CPU #0: nip=0xc0000000000b715c thread_id=91678
(qemu) 

Regards,
-Satheesh
