### ISSUE TITLE
qemu crashes with assertion `fdctrl->dma' failed

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#12]
Steps to re-produce:
1. Get the `device-crash-test` script from qemu git under scripts folder.
2. Run the script with default qemu binary.
./device-crash-test /usr/bin/qemu-system-ppc64
3. Check the output
...
```
INFO: running test case: machine=powernv binary=/usr/bin/qemu-system-ppc64 device=isa-fdc accel=tcg
WARNING: qemu received signal -6: /usr/bin/qemu-system-ppc64 -chardev socket,id=mon,path=/var/tmp/qemu-49183-monitor.sock -mon chardev=mon,mode=control -display none -vga none -S -machine powernv,accel=tcg -device isa-fdc
CRITICAL: failed: machine=powernv binary=/usr/bin/qemu-system-ppc64 device=isa-fdc accel=tcg
CRITICAL: cmdline: /usr/bin/qemu-system-ppc64 -S -machine powernv,accel=tcg -device isa-fdc
CRITICAL: log: qemu-system-ppc64: hw/block/fdc.c:2702: isabus_fdc_realize: Assertion `fdctrl->dma' failed.
CRITICAL: exit code: -6
```

<cde:info> Mirrored with LTC bug #159874 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment From alexey@au1.ibm.com 2017-10-26 02:48:15 EDT-------
I posted a patch to replace assert() with a proper error report. But this is not something we support or care, really - there is no scenario when we would consider using floppy disc.

**Comment by nasastry** [comment]
Link to the patch is http://lists.nongnu.org/archive/html/qemu-devel/2017-10/msg05945.html

**Comment by cdeadmin** [comment]
Link to the patch is http://lists.nongnu.org/archive/html/qemu-devel/2017-10/msg05945.html

**Comment by cdeadmin** [comment]
------- Comment From lagarcia@br.ibm.com 2018-03-23 12:27:40 EDT-------
It seems this has never reached upstream. Should we retry or close this bug?

**Comment by aik** [comment]
A similar fix has been pushed out - https://git.qemu.org/?p=qemu.git;a=commitdiff;h=b3da5513;hp=089eac81e1d34d202471c0a023284f47f4c5f00e

So this might be eventually fixed as well but we can close it anyway as it is not what we support anyway.

**Comment by cdeadmin** [comment]
------- Comment From venkatb3@in.ibm.com 2018-06-12 02:23:44 EDT-------
This bug is not reproducible with upstream qemu.
