### ISSUE TITLE
Guest not boots with -machine kernel-irqchip=off

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#17]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=159924 </cde:info>

`/usr/bin/qemu-system-ppc64 -machine pseries,help` says 
...
pseries-2.10.kernel-irqchip=OnOffSplit (Configure KVM in-kernel irqchip)
...

Though seeing capitalized word in the help, only `on,off,split` is working.

So tried to boot with `kernel-irqchip=off` and guest doesn't boot.
```
\# /usr/bin/qemu-system-ppc64 --nographic -vga none -machine pseries,accel=kvm,kvm-type=HV,kernel-irqchip=off -m 2G,slots=32,maxmem=16G -device virtio-blk-pci,drive=rootdisk -drive file=/home/nasastry/hostos-3.0-ppc64le.qcow2,if=none,cache=none,id=rootdisk,format=qcow2 -net nic,model=virtio
```

...
guest stops booting at 

```
...
[    0.618380] synth uevent: /devices/vio: failed to send uevent
[    0.618382] vio vio: uevent: failed to send synthetic uevent
[    0.680205] ibmvscsi 71000002: SRP_VERSION: 16.a
[    0.680959] ibmvscsi 71000002: Maximum ID: 64 Maximum LUN: 32 Maximum Channel: 3
[    0.682034] scsi host0: IBM POWER Virtual SCSI Adapter 1.5.9
```

and not proceeding further, it doesn't respond with ctrl+c.
will attach the full guest console log.

**Comment by nasastry** [comment]
[kernel-irqchip_off.txt](https://github.com/open-power-host-os/qemu/files/1371280/kernel-irqchip_off.txt)
Attaching the guest console log.

**Comment by cdeadmin** [comment]
------- Comment From alexey@au1.ibm.com 2017-10-26 00:46:41 EDT-------
The reason for that is xive_enabled = true on POWER9 and arch/powerpc/kvm/book3s_xive_template.c simply ignores the fact that QEMU has not enabled XICS KVM device; and this is why it keeps working on POWER8.
I am working on a fix now.

**Comment by cdeadmin** [comment]
------- Comment From nasastry@in.ibm.com 2018-02-15 03:57:53 EDT-------
Tested on  qemu-system-ppc-2.11.0-1.rel.gite7153e0.el7.centos.ppc64le

Could able to boot the guest with kernel-irqchip=off

[root@zzfp365-lp1 scripts]# /usr/bin/qemu-system-ppc64 --nographic -vga none -machine pseries,accel=kvm,kvm-type=HV,kernel-irqchip=off -m 2G,slots=32,maxmem=16G -device virtio-blk-pci,drive=rootdisk -drive file=/home/nasastry/hostos-3.0-ppc64le.qcow2,if=none,cache=none,id=rootdisk,format=qcow2 -net nic,model=virtio

this bugzilla can be closed.
