### ISSUE TITLE
qemu kernel-irqchip help output is not clear and confusing

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#18]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=159926 </cde:info>

`qemu-system-ppc64 -machine pseries,help` output shows 
...
`kernel-irqchip=OnOffSplit (Configure KVM in-kernel irqchip)`

The above output is confusing and not clear. And that too capitalized word is not working. Valid word has to be in smaller case like (on, off, split).

Help should look like 
`kernel-irqchip=string (Configure KVM in-kernel irqchip. Valid values are on, off, split)`

**Comment by cdeadmin** [comment]
------- Comment From alexey@au1.ibm.com 2017-10-25 21:29:35 EDT-------
I posted a fix to qemu-devel@

**Comment by nasastry** [comment]
Link to the patch is 
http://lists.nongnu.org/archive/html/qemu-devel/2017-10/msg05907.html

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-05-25 12:38:49 EDT-------
Alexey, anything from the qemu list, yet?

**Comment by cdeadmin** [comment]
------- Comment From alexey@au1.ibm.com 2018-05-28 23:52:26 EDT-------
It has been merged to upstream and hostos-devel.
