### ISSUE TITLE
[memory hotplug/hotunplug]: qemu crashes with assertion failed from hw/virtio/vhost.c:649

### ISSUE THREAD

**Issue by MalleshKoti** [open-power-host-os/qemu#24]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=160580 </cde:info>

--- Description ---
Qemu crashes with : "qemu-system-ppc64: /builddir/build/BUILD/qemu/hw/virtio/vhost.c:649: vhost_commit: Assertion `r >= 0' failed."

--- Steps to reproduce ---
1. Boot in to guest 
2. Continuously hotplug memory
3. Try to hotunplug, hotunplug may fail
4. Reboot guest.
5. Now try to hotunplug memory continuously
6. reboot guest
Qemu crashes at the time of boot with the following messages :

LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin QEMU_AUDIO_DRV=none /usr/bin/qemu-kvm -name guest=virt-tests-vm1-mallesh,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-10-virt-tests-vm1-malle/master-key.aes -machine pseries-2.10,accel=kvm,usb=off,dump-guest-core=off -m size=9437184k,slots=16,maxmem=134217728k -realtime mlock=off -smp 32,sockets=32,cores=1,threads=1 -numa node,nodeid=0,cpus=0-15,mem=4608 -numa node,nodeid=1,cpus=16-31,mem=4608 -uuid 1179b620-f726-4045-8d73-6ce27ff71035 -display none -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-10-virt-tests-vm1-malle/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device qemu-xhci,id=usb,bus=pci.0,addr=0x3 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x2 -drive file=/home/mallesh/avocado-fvt-wrapper/data/avocado-vt/images/hostos-3.0-ppc64le.qcow2,format=qcow2,if=none,id=drive-scsi0-0-0-0 -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=1 -netdev tap,fd=29,id=hostnet0,vhost=on,vhostfd=31 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:87:88:89,bus=pci.0,addr=0x1 -chardev pty,id=charserial0 -device spapr-vty,chardev=charserial0,reg=0x30000000 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -msg timestamp=on
2017-10-25T09:28:23.419250Z qemu-system-ppc64: -chardev pty,id=charserial0: char device redirected to /dev/pts/4 (label charserial0)
2017-10-25T09:34:08.409539Z qemu-system-ppc64: used ring relocated for ring 2
qemu-system-ppc64: /builddir/build/BUILD/qemu/hw/virtio/vhost.c:649: vhost_commit: Assertion `r >= 0' failed.
2017-10-25 09:34:08.891+0000: shutting down, reason=crashed

**Comment by cdeadmin** [comment]
------- Comment From KURZGREG@fr.ibm.com 2017-11-22 04:07:14 EDT-------
Fixed upstream by commit:

https://git.qemu.org/?p=qemu.git;a=commit;h=82512483940c756e2db1bd67ea91b02bc29c5e01

**Comment by laggarcia** [comment]
This is available in hostos-devel. @MalleshKoti, could you please verify?

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-02-06 17:49:03 EDT-------
Can we get this tested?
