### ISSUE TITLE
[HostOS Sprint 4][Kernel] leaking addresses

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#29]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=161185 </cde:info>

Recently there is a release of './leaking_addresses.pl' from Linux source code.
Find more discussion at:
http://www.openwall.com/lists/kernel-hardening/2017/11/07/5

When I ran the script on HostOS machine seeing the following leaks:
\# ./leaking_addresses.pl
/proc/1358/syscall: 238 0x7 0x7fffc4bb9ad0 0x18 0xffffffffffffffff 0xfffffffffff88a9c 0x0 0x7fffc4bb9ab0 0x7fff9c785a18
/proc/2770/status: SigIgn:	fffffffe7ffab4fe
/proc/14875/status: SigIgn:	fffffffffffffeff
/proc/14877/status: SigIgn:	fffffffffffffef8
/proc/14878/status: SigIgn:	fffffffffffffef8
/proc/14879/status: SigIgn:	fffffffffffffef8
/proc/14880/status: SigIgn:	fffffffffffffef8
/proc/14881/status: SigIgn:	fffffffffffffef8
/proc/14882/status: SigIgn:	fffffffffffffef8
/proc/14883/status: SigIgn:	fffffffffffffef8
/proc/14884/status: SigIgn:	fffffffffffffef8
/proc/1396/fdinfo/8: sigmask:	fffffffe7ffbfeff
/proc/1358/task/1358/syscall: 238 0x7 0x7fffc4bb9ad0 0x18 0xffffffffffffffff 0xfffffffffffce717 0x0 0x7fffc4bb9ab0 0x7fff9c785a18
/proc/2770/task/2770/status: SigIgn:	fffffffe7ffab4fe
/proc/2770/task/2771/status: SigIgn:	fffffffe7ffab4fe
/proc/14875/task/14875/status: SigIgn:	fffffffffffffeff
/proc/14877/task/14877/status: SigIgn:	fffffffffffffef8
/proc/14878/task/14878/status: SigIgn:	fffffffffffffef8
/proc/14879/task/14879/status: SigIgn:	fffffffffffffef8
/proc/14880/task/14880/status: SigIgn:	fffffffffffffef8
/proc/14881/task/14881/status: SigIgn:	fffffffffffffef8
/proc/14882/task/14882/status: SigIgn:	fffffffffffffef8
/proc/14883/task/14883/status: SigIgn:	fffffffffffffef8
/proc/14884/task/14884/status: SigIgn:	fffffffffffffef8
/proc/1396/task/1396/fdinfo/8: sigmask:	fffffffe7ffbfeff

Kernel:
4.13.0-4.rel.git49564cb.el7.centos.ppc64le

Please let me know any additional information need to be provided. Thanks!!

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From nasastry@in.ibm.com 2017-11-10 05:14:22 EDT-------

**Comment by cdeadmin** [comment]
------- Comment From ellerman@au1.ibm.com 2017-11-15 19:36:10 EDT-------
Yeah the script as run is wrong for powerpc, as Rick says our kernel addresses are different.

Time would be better spent engaging with the upstream discussion rather than filing bugs internally.
