### ISSUE TITLE
[power9][DD 2.2][meltdown/spectre] qemu gets crashed with cap-ibs="workaround"

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/qemu#36]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=164568 </cde:info>

qemu-kvm gets crashed during guest bootup while starting with cap-ibs="workaround"

Env:

```
**Host:**

FW: # lsmcode
Version of System Firmware : 
 Product Name          : OpenPOWER Firmware
 Product Version       : open-power-SUPERMICRO-P9DSU-V1.03-20180205-imp
 Product Extra         : 	occ-577915f
 Product Extra         : 	skiboot-v5.9-240-g081882690163-pcbedce4
 Product Extra         : 	petitboot-v1.6.6-p019c87e
 Product Extra         : 	sbe-095e608
 Product Extra         : 	machine-xml-fb5f933
 Product Extra         : 	hostboot-9bfb201
 Product Extra         : 	linux-4.14.13-openpower1-p78d7eee

Kernel: 4.15.0-4.dev.gita707e6c.el7.centos.ppc64le
qemu: qemu-2.11.50-2.dev.git59cc362.el7.centos.ppc64le

# ls /sys/firmware/devicetree/base/ibm,opal/fw-features/*/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/fw-bcctrl-serialized/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/fw-count-cache-disabled/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/fw-l1d-thread-split/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/inst-l1d-flush-trig2/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/inst-spec-barrier-ori31,31,0/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/needs-l1d-flush-msr-hv-1-to-0/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/needs-l1d-flush-msr-pr-0-to-1/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/needs-spec-barrier-for-bound-checks/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/speculation-policy-favor-security/enabled
/sys/firmware/devicetree/base/ibm,opal/fw-features/tm-suspend-mode/enabled

---------------------
**Guest:**
Kernel: 4.15.0-4.dev.gita707e6c.el7.centos.ppc64le

```
Steps to reproduce:
```
 /usr/bin/qemu-kvm -M pseries,cap-sbbc="workaround",cap-cfpc="workaround",cap-ibs="workaround" -enable-kvm -nographic -serial /dev/pts/3 -monitor stdio /home/sath/avocado-fvt-wrapper/data/avocado-vt/images/hostos-ppc64le.qcow2
QEMU 2.11.50 monitor - type 'help' for more information
(qemu) info cpus
* CPU #0: nip=0x000000000dbe0c4c thread_id=36598
(qemu) info status
VM status: running
(qemu) qemu-system-ppc64: /builddir/build/BUILD/qemu/hw/ppc/spapr_hcall.c:1702: h_get_cpu_characteristics: Assertion `safe_indirect_branch == 0x00' failed.
Aborted
```
Guest Console:
```
SLOF **********************************************************************
QEMU Starting
 Build Date = Jan 31 2018 12:47:36
 FW Version = mockbuild@ release 20170724
 Press "s" to enter Open Firmware.

Populating /vdevice methods
Populating /vdevice/vty@71000000
Populating /vdevice/nvram@71000001
Populating /vdevice/l-lan@71000002
Populating /vdevice/v-scsi@71000003
       SCSI: Looking for devices
          8000000000000000 DISK     : "QEMU     QEMU HARDDISK    2.5+"
          8200000000000000 CD-ROM   : "QEMU     QEMU CD-ROM      2.5+"
Populating /pci@800000020000000
                     00 0000 (D) : 1234 1111    qemu vga
                     00 0800 (D) : 1033 0194    serial bus [ usb-xhci ]
No NVRAM common partition, re-initializing...
Installing QEMU fb



Scanning USB 
  XHCI: Initializing
    USB Keyboard 
    USB mouse 
No console specified using screen & keyboard
     
  Welcome to Open Firmware

  Copyright (c) 2004, 2017 IBM Corporation All rights reserved.
  This program and the accompanying materials are made available
  under the terms of the BSD License available at
  http://www.opensource.org/licenses/bsd-license.php


Trying to load:  from: /vdevice/v-scsi@71000003/disk@8000000000000000 ...   Successfully loaded
````

**Comment by cdeadmin** [comment]
------- Comment From KURZGREG@fr.ibm.com 2018-02-13 05:06:13 EDT-------
This issue was detected last week thanks to the Coverity static analysis software.
The fix is already upstream:

https://git.qemu.org/?p=qemu.git;a=commit;h=fa86f59234919b479b7e8da6b0dc2dad894a5eac

**Comment by cdeadmin** [comment]
------- Comment From surajjs@au1.ibm.com 2018-02-13 19:22:13 EDT-------
Yeah my bad. The only valid values for cap-ibs are broken or fixed. But I made a mistake and didn't verify this properly so we will allow a value of workaround and then hit an assert which will crash qemu.

I have a fix which I plan to send upstream today.

This is similar, however slightly different to the bug Greg fixed.

**Comment by cdeadmin** [comment]
------- Comment From KURZGREG@fr.ibm.com 2018-02-14 02:45:52 EDT-------
(In reply to comment #3)
&gt; Yeah my bad. The only valid values for cap-ibs are broken or fixed. But I
&gt; made a mistake and didn't verify this properly so we will allow a value of
&gt; workaround and then hit an assert which will crash qemu.
&gt; 
&gt; I have a fix which I plan to send upstream today.
&gt; 
&gt; This is similar, however slightly different to the bug Greg fixed.

Oops you're right, I had misread the initial report was mentioning &quot;workaround&quot;, not &quot;fixed&quot; :)

**Comment by cdeadmin** [comment]
------- Comment From surajjs@au1.ibm.com 2018-02-19 19:59:46 EDT-------
Patch is now upstream as:
4f5b039d2b ppc/spapr-caps: Disallow setting workaround for spapr-cap-ibs

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2018-02-27 04:44:31 EDT-------
When are we getting this in hostos?

**Comment by cdeadmin** [comment]
------- Comment From satheera@in.ibm.com 2018-04-09 07:18:49 EDT-------
# /usr/bin/qemu-kvm -version
QEMU emulator version 2.11.91
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

/usr/bin/qemu-kvm -M pseries,cap-ibs=&quot;workaround&quot; -enable-kvm -nographic -serial /dev/null -monitor stdio /home/sath/hostos-ppc64le.qcow2
QEMU 2.11.91 monitor - type 'help' for more information
(qemu) qemu-system-ppc64: Requested safe indirect branch capability level &quot;workaround&quot; not valid, try cap-ibs=broken
