### ISSUE TITLE
qemu segfaults with dump-guest-memory

### ISSUE THREAD

**Issue by nasastry** [open-power-host-os/qemu#8]
Environment:
HostOS 
\# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
SIG_FAMILY="AltArch ppc64le"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

\# uname -a
Linux zzfp365-lp1.aus.stglabs.ibm.com 4.13.0-4.rel.git49564cb.el7.centos.ppc64le #1 SMP Fri Sep 22 22:49:59 -03 2017 ppc64le ppc64le ppc64le GNU/Linux

\# rpm -qa | grep qemu
qemu-common-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le
qemu-system-ppc-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le
qemu-img-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le
libvirt-daemon-driver-qemu-3.6.0-3.rel.gitdd9401b.el7.centos.ppc64le
qemu-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le
ipxe-roms-qemu-20170123-1.git4e85b27.el7_4.1.noarch
qemu-system-x86-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le

Steps to re-produce:

\# qemu-system-ppc64 -M none -nographic -m 256
QEMU 2.10.0 monitor - type 'help' for more information
(qemu) dump-guest-memory /dev/null
Segmentation fault

<cde:info> Mirrored with LTC bug #159859 </cde:info>

**Comment by gkurz** [comment]
This issue is already fixed upstream:

https://github.com/qemu/qemu/commit/b1fde1ef5106c92dd12f1f0cfcb8c76e57d7f681

The new behavior is to reject dump when you don't have a CPU:

(qemu) dump-guest-memory /dev/null
this feature or command is not currently supported

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-12-20 03:50:30 EDT-------
Tested on release branch.

[root@ltczzj3 qemu-iotests]# uname -r
4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
[root@ltczzj3 qemu-iotests]# qemu-system-ppc64 -M none -nographic -m 256
QEMU 2.11.0 monitor - type 'help' for more information
(qemu) dump-guest-memory /dev/null
this feature or command is not currently supported
